name: CI Pipeline

on:
  push:
    branches: [ main, development ]
  pull_request:
    branches: [ main, development ]

jobs:
  test:
    name: Test Suite
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run ESLint
      run: npm run lint
      
    - name: Run TypeScript type check
      run: npm run type-check
      
    - name: Run tests
      run: npm run test:coverage
      env:
        # Mock environment variables for tests
        SPOTIFY_CLIENT_ID: test_client_id
        SPOTIFY_CLIENT_SECRET: test_client_secret
        SPOTIFY_REDIRECT_URI: http://localhost:3000/api/auth/callback
        OPENAI_API_KEY: test_openai_key
        NEXTAUTH_URL: http://localhost:3000
        NEXTAUTH_SECRET: test_secret

  build:
    name: Build Application
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build application
      run: npm run build
      env:
        # Required for build but using dummy values
        SPOTIFY_CLIENT_ID: dummy_client_id
        SPOTIFY_CLIENT_SECRET: dummy_client_secret
        SPOTIFY_REDIRECT_URI: http://localhost:3000/api/auth/callback
        OPENAI_API_KEY: dummy_openai_key
        NEXTAUTH_URL: http://localhost:3000
        NEXTAUTH_SECRET: dummy_secret

  audit:
    name: Security Audit
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run npm audit
      run: npm audit --audit-level=moderate